name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Python
        uses: actions/setup-python@v2 
        with:
          python-version: '3.12'  

      - name: Install dependencies
        run: |
          cd health-calculator-service  # Navigate to the folder where the Makefile is located
          make init  # Install dependencies via pip

      - name: Build Docker image
        run: |
          cd health-calculator-service  # Navigate to the project folder
          make build  # Runs 'make build' to build the Docker image

      - name: Run tests
        run: |
          cd health-calculator-service  # Navigate to the project folder
          make test  # Execute the unit tests

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2 
        with:
          app-name: 'health-calculator'  
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  
          package: ./health-calculator-service  
